import catalogData from "@/data/catalog.json";
import { SHOP_PUBLIC_URL } from "./config";

// src/data/catalog.json is generated by scripts/gelato-build-catalog.mjs, not
// hand-edited. Prices in it already include the shipping markup — shipping is
// folded into the price and Stripe shows free shipping.

export type CatalogVariant = {
  sku: string;
  sizeName: string;
  // Gelato product identifier for this exact blank/colour/size/print.
  productUid: string;
  priceCents: number;
};

export type CatalogProduct = {
  id: number;
  title: string;
  description: string;
  // Single representative colour name ("" for non-apparel). The storefront
  // hides the colour picker for single-colour products.
  color: string;
  // File under public/designs that Gelato fetches as the print file; null means
  // the original was text-only and still needs artwork before it can be ordered.
  designFile: string | null;
  needsArtwork: boolean;
  variants: CatalogVariant[];
};

export const CATALOG_CURRENCY: string = catalogData.currency;

const PRODUCTS: CatalogProduct[] = catalogData.products as CatalogProduct[];
const BY_ID = new Map<number, CatalogProduct>(PRODUCTS.map((p) => [p.id, p]));

// Only products that can actually be fulfilled (have a design and ≥1 variant)
// are shown in the storefront; artwork-pending products stay hidden until fixed.
export function listProducts(): CatalogProduct[] {
  return PRODUCTS.filter((p) => p.variants.length > 0 && !p.needsArtwork);
}

export function getProduct(id: number): CatalogProduct | undefined {
  return BY_ID.get(id);
}

export function findVariant(product: CatalogProduct, sku: string): CatalogVariant | undefined {
  return product.variants.find((v) => v.sku === sku);
}

// Resolve a SKU back to its product + variant — used by the order path to map a
// purchased line to its Gelato productUid and print file.
export function findBySku(
  sku: string,
): { product: CatalogProduct; variant: CatalogVariant } | null {
  for (const product of PRODUCTS) {
    const variant = product.variants.find((v) => v.sku === sku);
    if (variant) return { product, variant };
  }
  return null;
}

export function lowestPriceCents(product: CatalogProduct): number | null {
  if (product.variants.length === 0) return null;
  return Math.min(...product.variants.map((v) => v.priceCents));
}

// The variant shape the storefront (product page + articles API) renders.
export type StorefrontVariant = {
  sku: string;
  sizeName: string;
  appearanceName: string;
  appearanceColorValue: string;
  price: number;
  stock: number;
};

// Project catalog variants into the storefront view. Colour value is blank and
// stock is a sentinel because Gelato is make-to-order (no stock) and catalog
// products are single-colour; keeping the projection here stops the page and the
// API route from drifting on those placeholders.
export function storefrontVariants(product: CatalogProduct): StorefrontVariant[] {
  return product.variants.map((v) => ({
    sku: v.sku,
    sizeName: v.sizeName,
    appearanceName: product.color,
    appearanceColorValue: "",
    price: v.priceCents / 100,
    stock: 1,
  }));
}

// Path under /public for the product's artwork, used as the storefront image
// until real Gelato mockups are generated. null when artwork is pending.
export function productImagePath(product: CatalogProduct): string | null {
  return product.designFile ? `/designs/${product.designFile}` : null;
}

// Absolute, publicly reachable URL of the print file for Gelato to download at
// order time. Throws for artwork-pending products — they must not be ordered.
export function designUrlFor(product: CatalogProduct): string {
  if (!product.designFile) {
    throw new Error(`product ${product.id} (${product.title}) has no design file`);
  }
  return `${SHOP_PUBLIC_URL.replace(/\/$/, "")}/designs/${product.designFile}`;
}
