// AUTO-GENERATED from faq.spreadconnect.app EU shipping calculator on 2026-05-19.
// Each tier: customer cart value (excl shipping) >= threshold → SC charges us shipping price.
// All values in EUR. We then mark up the per-item price to absorb this cost (see SHIPPING_MARKUP_CENTS).

export type ShippingTier = { minCartEur: number; priceEur: number };
export type ShippingZone = { name: string; tiers: ShippingTier[]; isoCountries: string[] };

export const SC_EU_SHIPPING_ZONES: ShippingZone[] = [
  {
    name: "DOMESTIC", // Germany + tightly-coupled territories, cheapest top-tier.
    tiers: [
      { minCartEur: 0.01, priceEur: 3.25 },
      { minCartEur: 5.01, priceEur: 3.99 },
      { minCartEur: 12.01, priceEur: 4.6 },
      { minCartEur: 40.01, priceEur: 6.5 },
      { minCartEur: 75.01, priceEur: 10.0 },
      { minCartEur: 125.02, priceEur: 13.01 },
    ],
    isoCountries: ["DE", "IM", "MF"],
  },
  {
    name: "EU_NEAR", // BeNeLux, Scandi neighbours, Canary Is., Monaco, Greece.
    tiers: [
      { minCartEur: 0.01, priceEur: 3.25 },
      { minCartEur: 5.01, priceEur: 3.55 },
      { minCartEur: 12.01, priceEur: 4.99 },
      { minCartEur: 40.01, priceEur: 6.99 },
      { minCartEur: 75.01, priceEur: 12.25 },
      { minCartEur: 125.01, priceEur: 15.99 },
    ],
    isoCountries: ["AT", "BE", "DK", "GR", "IC", "LU", "MC", "NL", "SE"],
  },
  {
    name: "EU_WEST", // Western / southern / Poland.
    tiers: [
      { minCartEur: 0.01, priceEur: 3.99 },
      { minCartEur: 5.01, priceEur: 4.65 },
      { minCartEur: 12.01, priceEur: 5.99 },
      { minCartEur: 40.01, priceEur: 7.25 },
      { minCartEur: 75.01, priceEur: 12.25 },
      { minCartEur: 125.01, priceEur: 17.99 },
    ],
    isoCountries: ["AX", "ES", "FI", "FR", "GG", "IE", "IT", "JE", "PL"],
  },
  {
    name: "EU_SOUTHEAST", // Eastern EU members — pricier brackets.
    tiers: [
      { minCartEur: 0.01, priceEur: 4.99 },
      { minCartEur: 5.01, priceEur: 6.99 },
      { minCartEur: 59.99, priceEur: 9.99 },
      { minCartEur: 99.99, priceEur: 13.99 },
      { minCartEur: 175.01, priceEur: 19.99 },
    ],
    isoCountries: ["BG", "CY", "CZ", "EE", "HR", "HU", "LT", "LV", "PT", "RO", "SI", "SK"],
  },
  {
    name: "EU_BALKANS", // Albania, BiH, NMK, microstates Andorra/Malta/San Marino.
    tiers: [
      { minCartEur: 0.01, priceEur: 4.99 },
      { minCartEur: 5.01, priceEur: 5.99 },
      { minCartEur: 12.01, priceEur: 6.55 },
      { minCartEur: 40.01, priceEur: 7.25 },
      { minCartEur: 75.01, priceEur: 13.25 },
      { minCartEur: 125.01, priceEur: 20.75 },
    ],
    isoCountries: ["AD", "AL", "BA", "MK", "MT", "SM"],
  },
  {
    name: "ROW",
    tiers: [
      { minCartEur: 0.01, priceEur: 9.99 },
      { minCartEur: 24.99, priceEur: 16.99 },
      { minCartEur: 59.99, priceEur: 24.99 },
    ],
    isoCountries: [
      "AE",
      "AG",
      "AI",
      "AM",
      "AN",
      "AO",
      "AW",
      "AZ",
      "BB",
      "BD",
      "BF",
      "BH",
      "BI",
      "BJ",
      "BM",
      "BN",
      "BO",
      "BS",
      "BT",
      "BW",
      "BZ",
      "CD",
      "CF",
      "CG",
      "CI",
      "CK",
      "CM",
      "CO",
      "CR",
      "CV",
      "DM",
      "DO",
      "EC",
      "EG",
      "ER",
      "ET",
      "FJ",
      "FK",
      "FO",
      "GA",
      "GB",
      "GD",
      "GE",
      "GH",
      "GI",
      "GL",
      "GM",
      "GN",
      "GQ",
      "GT",
      "GU",
      "GW",
      "GY",
      "HK",
      "ID",
      "IL",
      "IN",
      "IS",
      "JM",
      "JO",
      "JP",
      "KE",
      "KH",
      "KI",
      "KM",
      "KN",
      "KW",
      "KY",
      "KZ",
      "LA",
      "LC",
      "LK",
      "LS",
      "MA",
      "ME",
      "MG",
      "ML",
      "MM",
      "MN",
      "MO",
      "MR",
      "MS",
      "MU",
      "MV",
      "MW",
      "MX",
      "MY",
      "MZ",
      "NA",
      "NE",
      "NG",
      "NP",
      "NR",
      "OM",
      "PA",
      "PE",
      "PH",
      "PK",
      "PM",
      "PW",
      "PY",
      "QA",
      "RS",
      "RW",
      "SA",
      "SB",
      "SC",
      "SH",
      "SL",
      "SN",
      "SR",
      "ST",
      "SV",
      "SZ",
      "TC",
      "TD",
      "TG",
      "TH",
      "TJ",
      "TL",
      "TM",
      "TN",
      "TR",
      "TT",
      "TZ",
      "UG",
      "UY",
      "UZ",
      "VA",
      "VC",
      "VE",
      "VG",
      "VN",
      "WF",
      "XK",
      "YT",
      "ZM",
      "ZW",
    ],
  },
];

// Flat union of all SC-EU-deliverable countries, alphabetised — drop into
// Stripe checkout `allowed_countries`.
export const SC_EU_DELIVERABLE_ISO: string[] = [
  "AD",
  "AE",
  "AG",
  "AI",
  "AL",
  "AM",
  "AN",
  "AO",
  "AT",
  "AW",
  "AX",
  "AZ",
  "BA",
  "BB",
  "BD",
  "BE",
  "BF",
  "BG",
  "BH",
  "BI",
  "BJ",
  "BM",
  "BN",
  "BO",
  "BS",
  "BT",
  "BW",
  "BZ",
  "CD",
  "CF",
  "CG",
  "CI",
  "CK",
  "CM",
  "CO",
  "CR",
  "CV",
  "CY",
  "CZ",
  "DE",
  "DK",
  "DM",
  "DO",
  "EC",
  "EE",
  "EG",
  "ER",
  "ES",
  "ET",
  "FI",
  "FJ",
  "FK",
  "FO",
  "FR",
  "GA",
  "GB",
  "GD",
  "GE",
  "GG",
  "GH",
  "GI",
  "GL",
  "GM",
  "GN",
  "GQ",
  "GR",
  "GT",
  "GU",
  "GW",
  "GY",
  "HK",
  "HR",
  "HU",
  "IC",
  "ID",
  "IE",
  "IL",
  "IM",
  "IN",
  "IS",
  "IT",
  "JE",
  "JM",
  "JO",
  "JP",
  "KE",
  "KH",
  "KI",
  "KM",
  "KN",
  "KW",
  "KY",
  "KZ",
  "LA",
  "LC",
  "LK",
  "LS",
  "LT",
  "LU",
  "LV",
  "MA",
  "MC",
  "ME",
  "MF",
  "MG",
  "MK",
  "ML",
  "MM",
  "MN",
  "MO",
  "MR",
  "MS",
  "MT",
  "MU",
  "MV",
  "MW",
  "MX",
  "MY",
  "MZ",
  "NA",
  "NE",
  "NG",
  "NL",
  "NP",
  "NR",
  "OM",
  "PA",
  "PE",
  "PH",
  "PK",
  "PL",
  "PM",
  "PT",
  "PW",
  "PY",
  "QA",
  "RO",
  "RS",
  "RW",
  "SA",
  "SB",
  "SC",
  "SE",
  "SH",
  "SI",
  "SK",
  "SL",
  "SM",
  "SN",
  "SR",
  "ST",
  "SV",
  "SZ",
  "TC",
  "TD",
  "TG",
  "TH",
  "TJ",
  "TL",
  "TM",
  "TN",
  "TR",
  "TT",
  "TZ",
  "UG",
  "UY",
  "UZ",
  "VA",
  "VC",
  "VE",
  "VG",
  "VN",
  "WF",
  "XK",
  "YT",
  "ZM",
  "ZW",
];

export function shippingZoneFor(iso: string): ShippingZone | undefined {
  return SC_EU_SHIPPING_ZONES.find((z) => z.isoCountries.includes(iso));
}

export function shippingCostEur(iso: string, cartEur: number): number | null {
  const z = shippingZoneFor(iso);
  if (!z) return null;
  let cost = z.tiers[0].priceEur;
  for (const t of z.tiers) if (cartEur >= t.minCartEur) cost = t.priceEur;
  return cost;
}
